version: '1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #./userBackend
    #image: monkey-codes/spring-boot-restful
    #container_name: web
    #ports:
      - "8080:8080"
    links:
      - db

  db:
     image: mongo
     container_name: db
     volumes:
      - $HOME/data/db:/data/db
     # - data-mongo:/data/db
     #hostname: mongodb