version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_backend
    image: user_backend_img
    ports:
          - "8080:8080"
          - "8000:8000"
    links:
      - db

  db:
     image: mongo
     container_name: user_db
     volumes:
          - /data/db:/data/db
     ports:
          - "27017:27017"

